### ISSUE TITLE
Exploring Docker/Docker Compose with a GUI Web App: Is It Possible?

### ISSUE THREAD

**Issue by PesterMess** [DevilXD/TwitchDropsMiner#657]
I'm really interested in using this in a non-desktop environment, potentially through a Docker container with a web UI or web app. I understand if this isn't on your roadmap, but it could really benefit those who already use Twitch farming and prefer to do it through Docker. I’d love to hear your thoughts on this!

**Comment by TheLovinator1** [comment]
Use something like this: https://github.com/mviereck/x11docker or look what @Valentin-Metz did here: https://github.com/Valentin-Metz/TwitchDropsMiner

**Comment by Valentin-Metz** [comment]
My fork is still working and maintained. If you encounter any issues, please let me know.

**Comment by PesterMess** [comment]
> My fork is still working and maintained. If you encounter any issues, please let me know.

I'm very new to using Docker through command line, so if you can provide me with a docker compose let me know. I only use [DockGE](https://github.com/louislam/dockge) for my usage.

**Comment by Valentin-Metz** [comment]
You can run the command suggested in https://github.com/Valentin-Metz/TwitchDropsMiner/blob/master/Dockerfile or write a compose file (though you shouldn't need one as this is a standalone service).

**Comment by TheLovinator1** [comment]
```yaml
version: '3.8'

services:
  twitch_drops_miner:
    image: ghcr.io/valentin-metz/twitchdropsminer:master
    container_name: twitch_drops_miner
    restart: unless-stopped
    volumes:
      - ./cookies.jar:/TwitchDropsMiner/cookies.jar
      - ./settings.json:/TwitchDropsMiner/settings.json:ro
      - /etc/localtime:/etc/localtime:ro

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: --cleanup --include-restarting --include-stopped --interval 3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
```

Something like this, I used 3600 instead of 60 so you don't get rate limited.

You need to modify `./cookies.jar` and `./settings.json`.
